### ISSUE TITLE
Intro presentation does not work if there is a space in the path to lib

### ISSUE THREAD

**Issue by antoine-sachet** [wahani/REPLesentR#1]
Trying to run the intro presentation but it fails because the path to `Introduction.plain` is not quoted in the call to `pandoc`. Spaces in windows paths are sadly quite common.

This is the error message:

```
output file: C:/Users/Antoine Sachet/Documents/R/win-library/3.5/REPLesentR/Introduction.md

executing pandoc   -t plain -o C:/Users/Antoine Sachet/Documents/R/win-library/3.5/REPLesentR/Introduction.plain "C:/Users/Antoine Sachet/Documents/R/win-library/3.5/REPLesentR/Introduction_utf8.md"

pandoc.exe: Sachet/Documents/R/win-library/3.5/REPLesentR/Introduction.plain: openBinaryFile: does not exist (No such file or directory)

Error in (function (input, input_utf8, format, ext, cfg)  : 
  conversion failed
```

This would work if the output file (after `-o`) was quoted, like the path to `Introduction.md`.

Cheers,
Antoine

**Comment by wahani** [comment]
Hi, sorry to hear to that. That is a bad omen if the standard intro example is not working! Thanks for providing the suggestion.

The function I use for compiling the document is simply `knitr::pandoc(fileName, format = "plain")`. It is there that we have to get the quotes correct. I am not sure if that is possible. Until I find the time for a fix, you may copy the file into your working directory and experiment from there.(?)

```
file.copy("C:/Users/Antoine Sachet/Documents/R/win-library/3.5/REPLesentR/Introduction.Rmd", "Introduction.Rmd")
introduction <- REPLesentR::newPresentation("Introduction.Rmd")
introduction$start()
```

**Comment by wahani** [comment]
I have implemented a work around to resolve this issue. Unfortunately I do not see an easy solution to this, since the error is raised in `knitr::pandoc`. Maybe this can be resolved using the pandoc options file, I am not sure.

There is actually no need to compile the intro presentation in every call to `introPresentation`. So instead we just load it. If we detect spaces in the path, a warning is raised, so users may have an easier time fixing it.

@antoine-sachet you can install the latest version with:

```
devtools::install_github("wahani/REPLesentR")
```

If you find the time, can you verify that the fix is working for you?

**Comment by antoine-sachet** [comment]
Thanks for the quick response! The fix is working, the intro presentation is now working fine.

I think the warning is useful but obviously it would be better if it worked :)

```
executing pandoc   -t plain -o C:\Users\Antoine Sachet\Projects\R-training\Introduction.plain "C:\Users\Antoine Sachet\Projects\R-training\Introduction_utf8.md"
pandoc.exe: Sachet\Projects\R-training\Introduction.plain: openBinaryFile: does not exist (No such file or directory)
Error in (function (input, input_utf8, format, ext, cfg)  : 
  conversion failed
In addition: Warning message:
In read(fileName) :
  Detected spaces in 'C:\Users\Antoine Sachet\Projects\R-training\Introduction.Rmd'. In case of errors, try to remove them.
```
I have had a closer look at the error and `knitr::pandoc` calls `knitr:::pandoc_one` which contains the following bit of code:

```
out = unname(if (!is.na(cfg["o"])) 
        cfg["o"]
    else {
        if (!is.na(cfg["output"])) 
            cfg["output"]
        else {
            sub_ext(input, if (is.na(ext)) 
                pandoc_ext(format)
            else ext)
        }
    })
    cfg = cfg[setdiff(names(cfg), c("o", "output", "t"))]
    cmd = paste("pandoc", pandoc_arg(cfg), pandoc_arg(cmn), "-t", 
        format, "-o", out, paste(shQuote(input_utf8), collapse = " "))
```

I am not sure why `out` is not quoted in `cmd` while `input_utf8` is. There might be a good reason or it might just be an oversight! Looks like you can override the default output using the "o" or "output" option in the pandoc conf.

**Comment by antoine-sachet** [comment]
https://github.com/yihui/knitr/issues/1644

**Comment by wahani** [comment]
Thanks for your research and for opening the issue!

**Comment by antoine-sachet** [comment]
The knitr bug causing the issue is now fixed (https://github.com/yihui/knitr/commit/705e38b5d0cd299c9d0bf55b36cb05b87f5a6c19) so the intro presentation should work with the latest `knitr` version.

Maybe you could change the warning message to suggest installing the latest `knitr` version with `devtools::install_github`? The problem is that the warning will get raised even when the knitting actually works. Not sure what is the best way to proceed. Probably raise the warning until the knitr fix makes it to CRAN?

BTW nice package, keep up the good work :)

**Comment by wahani** [comment]
Thanks for coordinating the fix around this issue!

I will add the required knitr version to the DESCRIPTION and remove the warning. I will wait at least until knitr is updated on CRAN until I prepare a new release of this package.
